### ISSUE TITLE
app icons not working

### ISSUE THREAD

**Issue by sobakasu** [crramirez/uwp_bridge_java#1]
I'm not sure if something has changed in the windows 10 sdk, but the app icons don't work for me.
![missing_icon](https://user-images.githubusercontent.com/8692/33800697-89a2ee10-dd95-11e7-85bd-e343d4705715.jpg)

**Comment by crramirez** [comment]
I will test it and be right back.

**Comment by crramirez** [comment]
Update: It is happening to me also, after fall creators update. But I haven't had time to check it.
